#!/usr/bin/env python3
"""Install portable community skill/native profiles locally, never credentials or APIs.

Default is the current project. All conflicts are checked before files are changed.
Existing user configuration is preserved. Re-run with --check for drift verification.
"""
from __future__ import annotations
import argparse
import hashlib
import json
import os
from pathlib import Path
import sys
import tempfile
from native_routing import SKILL, policy, RoutingError

MARKER_START = "<!-- community-native-routing:start -->"
MARKER_END = "<!-- community-native-routing:end -->"
SKIP = {".git", ".secrets", "node_modules", ".wrangler", ".venv", ".development",
        "__pycache__", ".pytest_cache", "build", "screenshots", "test-results", "playwright-report"}
COMMON = """Read the supplied SKILL_ROOT/SKILL.md and its references/orchestration.md. Use the actual PROJECT_ROOT and bounded task packet. Preserve the frozen inputs, owned files and existing skill gates. Do not delegate, call model APIs, read credentials, publish, change accounts/DNS or submit live leads. Keep host permissions unchanged. Return artifacts, checks, findings, blockers and only actually observed runtime/model evidence. The task-specific rules below refine scope, never override the skill.
"""

def sha(data):
    return hashlib.sha256(data).hexdigest()

def safe(root, rel):
    path = Path(rel)
    if path.is_absolute() or ".." in path.parts:
        raise RoutingError("Install paths must stay within the project")
    result = root
    for part in path.parts:
        result = result / part
        if result.is_symlink():
            raise RoutingError("Refusing symlink install target: " + str(result))
    return result

def atomic(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    pending = None
    try:
        with tempfile.NamedTemporaryFile(dir=path.parent, prefix=".lp-install-", delete=False) as f:
            pending = Path(f.name)
            f.write(data)
            f.flush()
            os.fsync(f.fileno())
        os.replace(pending, path)
    finally:
        if pending and pending.exists():
            pending.unlink()

def render(runtime="both", inherit_models=False):
    p = policy()
    files = {}
    profiles = dict(p["roles"])
    for tier in ("fast", "standard", "deep", "critical"):
        profiles["compute-" + tier] = {"agent": "lp-" + tier, "tier": tier,
            "instruction": "Execute the bounded task specialization in the coordinator packet. This is an escalation/fallback profile, not a different business role."}
    profiles["inherit"] = {"agent": "lp-inherit", "tier": "inherit", "instruction": "Execute the task with the current host model and effort. Disclose that preferred routing was unavailable."}
    profiles["review-inherit"] = {"agent": "lp-reviewer-inherit", "tier": "inherit", "instruction": p["roles"]["review"]["instruction"]}
    profiles["review-critical"] = {"agent": "lp-reviewer-critical", "tier": "critical", "instruction": p["roles"]["review"]["instruction"]}
    for role, spec in profiles.items():
        if spec["agent"] is None:
            continue
        name = spec["agent"]
        instructions = COMMON + "\nTask specialization: " + spec["instruction"] + "\n"
        description = "Community landing page " + role + "; " + spec["tier"] + " compute."
        inherited = inherit_models or spec["tier"] == "inherit"
        if runtime in {"codex", "both"}:
            profile = p["providers"]["codex"].get(spec["tier"], {})
            lines = ["# Generated by community install_native.py; policy lives in config/routing.json.",
                     "name = " + json.dumps(name), "description = " + json.dumps(description)]
            if not inherited:
                lines += ["model = " + json.dumps(profile["model"]),
                          "model_reasoning_effort = " + json.dumps(profile["effort"])]
            if role.startswith("review"):
                lines.append('sandbox_mode = "read-only"')
            lines.append("developer_instructions = " + json.dumps(instructions))
            files[f".codex/agents/{name}.toml"] = ("\n".join(lines) + "\n").encode()
        if runtime in {"claude", "both"}:
            profile = p["providers"]["claude"].get(spec["tier"], {})
            lines = ["---", "name: " + name, "description: " + json.dumps(description),
                     "model: " + ("inherit" if inherited else profile["model"]), "maxTurns: 60"]
            if not inherited and profile["effort"] is not None:
                lines.append("effort: " + profile["effort"])
            # Haiku intentionally has no unsupported per-agent effort setting.
            if role.startswith("review"):
                lines.append("tools: Read, Grep, Glob, WebFetch, WebSearch")
            lines += ["disallowedTools: Agent", "---", "", instructions]
            files[f".claude/agents/{name}.md"] = ("\n".join(lines) + "\n").encode()
    return files

def instruction_block():
    return MARKER_START + "\n" + """## Community landing-page workflow

For landing-page work use `skills/community-landing-page-builder/SKILL.md`, not the legacy branded skill. Read that skill's `references/orchestration.md` before starting.

Use the host's native subagents and native model/effort controls only when actually available. OpenAI profiles are in `.codex/agents/`; Claude profiles are in `.claude/agents/`. Choose the matching provider, never cross-provider calls. No Jev, new API key, gateway or paid fallback is required. Run normal tasks sequentially with the current model when delegation/model selection is unavailable, and disclose it. A skill cannot create a missing host tool.

The coordinator owns task graph, shared contract, file reservations, integration and existing approvals. Cap cooperating workers at four; final acceptance and Lighthouse require their documented quiet/frozen stages. Ask for missing business facts only when material. Do not ask the owner to choose models. See the orchestration reference for capability preflight, native dispatch, bounded retries and the test prompt.
""" + MARKER_END + "\n"

def merge_instructions(previous):
    block = instruction_block()
    if MARKER_START in previous or MARKER_END in previous:
        if previous.count(MARKER_START) != 1 or previous.count(MARKER_END) != 1:
            raise RoutingError("Malformed managed instruction markers")
        start = previous.index(MARKER_START)
        end = previous.index(MARKER_END) + len(MARKER_END)
        if end < start:
            raise RoutingError("Malformed managed instruction order")
        return previous[:start] + block.rstrip("\n") + previous[end:]
    return previous + ("\n\n" if previous.strip() else "") + block

def install(project, runtime="both", *, copy_skill=False, inherit_models=False, check=False):
    root = Path(project).expanduser().resolve()
    if not root.is_dir():
        raise RoutingError("Project directory must exist")
    manifest_rel = "build/orchestration/install-manifest.json"
    manifest_path = safe(root, manifest_rel)
    previous = json.loads(manifest_path.read_text()) if manifest_path.exists() else {"files": {}}
    if not isinstance(previous, dict) or not isinstance(previous.get("files"), dict):
        raise RoutingError("Invalid installation manifest")
    files = render(runtime, inherit_models)
    if copy_skill:
        for source in sorted(SKILL.rglob("*")):
            rel = source.relative_to(SKILL)
            if any(x in SKIP for x in rel.parts) or source.name.startswith((".env", ".dev.vars")) or source.name in {"credentials.json", "secrets.json"} or source.suffix.lower() in {".pem", ".key", ".p12", ".pfx"}:
                continue
            if source.is_symlink():
                raise RoutingError("Refusing symlink skill source: " + str(rel))
            if source.is_file():
                files["skills/community-landing-page-builder/" + rel.as_posix()] = source.read_bytes()
    if not copy_skill and not safe(root, "skills/community-landing-page-builder/SKILL.md").is_file():
        raise RoutingError("Skill missing in project; add --copy-skill")
    for name in (["AGENTS.md", "CLAUDE.md"] if runtime == "both" else ["AGENTS.md" if runtime == "codex" else "CLAUDE.md"]):
        path = safe(root, name)
        files[name] = merge_instructions(path.read_text() if path.exists() else "").encode()
    config = ".codex/config.toml"
    config_bytes = b"# Native routing does not change the parent model or authentication.\n[agents]\nmax_concurrent_threads_per_session = 4\n"
    # Do not rewrite or append tables to an owner's existing configuration.
    if runtime in {"codex", "both"} and (not safe(root, config).exists() or config in previous["files"]):
        files[config] = config_bytes
    known_generated = {}
    for inherited in (False, True):
        for rel, data in render(runtime, inherited).items():
            known_generated.setdefault(rel, set()).add(sha(data))
    conflicts, changed = [], []
    for rel, data in files.items():
        target = safe(root, rel)
        old = target.read_bytes() if target.is_file() else None
        if target.exists() and not target.is_file():
            conflicts.append(rel)
        elif old != data:
            changed.append(rel)
            if rel in {"AGENTS.md", "CLAUDE.md"}:
                continue  # Only the delimited block is replaced; outside text is preserved.
            if old is not None and previous["files"].get(rel) != sha(old) and sha(old) not in known_generated.get(rel, set()):
                conflicts.append(rel)
    if conflicts:
        raise RoutingError("Local edits/unmanaged files would be overwritten: " + ", ".join(conflicts))
    if check:
        return {"status": "drift" if changed else "pass", "changed": changed, "runtime": runtime}
    for rel in changed:
        atomic(safe(root, rel), files[rel])
    hashes = dict(previous["files"])
    hashes.update({rel: sha(data) for rel, data in files.items()})
    atomic(manifest_path, (json.dumps({"schema_version": 1, "runtime": runtime, "files": hashes}, indent=2) + "\n").encode())
    return {"status": "installed", "changed": changed, "runtime": runtime,
            "note": "Reload/restart the host to discover profiles. No agents were launched and no account configuration was changed."}

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", type=Path, default=Path.cwd())
    parser.add_argument("--runtime", choices=["codex", "claude", "both"], default="both")
    parser.add_argument("--copy-skill", action="store_true")
    parser.add_argument("--inherit-models", action="store_true", help="Use host model/effort for unavailable or older profiles")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        result = install(args.project, args.runtime, copy_skill=args.copy_skill,
                         inherit_models=args.inherit_models, check=args.check)
        print(json.dumps(result, indent=2))
        return 1 if result["status"] == "drift" else 0
    except (RoutingError, OSError, ValueError) as error:
        print(json.dumps({"status": "blocked", "error": str(error)}))
        return 2

if __name__ == "__main__":
    sys.exit(main())
